'use strict';let the_exports;the_exports="undefined"===typeof exports?window:exports;
(function(Q){Q.TypeCzech=function(){function Fa(...W){function R(a,b){a=JSON.stringify(a);a=a.substring(1,a.length-1);console.log(`%c ${a}`,b)}function Ga(a){let b="";const c=a.toString();c.startsWith("class ")&&c.includes(" constructor(")&&(b=a.name);return b}function Ha(a){let b=!1;null!==a&&"undefined"!==typeof a&&"function"===typeof Object.getPrototypeOf(a)&&"object"===typeof a.prototype&&Ga(a)&&(b=!0);return b}function Ia(a){let b=!1;"string"===typeof a&&na.includes(a)&&(b=!0);return b}function oa(a){var b=
!1;if(null!==a&&"undefined"!==typeof a){const c=[];function d(e){e=Object.getPrototypeOf(e);null!==e&&(c.push(e.constructor.name),d(e))}b=Object.getPrototypeOf(a).constructor.name;na.includes(b)?b=[b]:(d(a),b=c)}return b}function pa(a){a=oa(a);let b=!1;a&&(b=a.shift());return b}function v(a){const b=pa(a);return b?b:null===a?"null":a instanceof Date?"Date":a instanceof RegExp?"RegExp":Array.isArray(a)?"Array":typeof a}function C(a){a=v(a);return"Array"===a?!0:"Object"===a}function qa(a){let b=!1;
eb.has(a)?b=!0:ra[a]&&(b=!0);return b}function K(a){return ra[a]?ra[a]:a}function X(a){return Ja[a]?Ja[a]:a}function ha(a){return a.replace(/"/g,"'")}function x(a){if("undefined"===typeof a)a="-un-defined-";else if("bigint"===typeof a)a=`${a}n`;else if("string"===typeof a)a=a.replace(/"/g,"'");else{const b=JSON.stringify(a);a="object"===typeof a?ha(b):b}return a}function fb(a,b){return"bigint"===typeof b?`${b}n`:"undefined"===typeof b?"-un-defined-":Number.isNaN(b)?"-NaN-":"function"===typeof b||
b&&b.constructor===RegExp?`${String(b).substring(0,30)} ...`:b}function E(a){a=JSON.stringify(a,fb);return x(a)}function q(a,b){return sa&&b?(a=`${b} - ${a}`,ta&&R(a,"background: #ee0; color: #F00"),a):a}function ua(a){if(0<Object.keys(a).length){const [b,c]=Object.entries(a)[0];a=q(` The key '${b}', which has a type of '${c}', is missing in the checked object`,"TC@46")}else a="";return a}function Y(a){if(a instanceof Date)var b="Invalid Date"==a;else a instanceof RegExp?b="/(?:)/"===a.toString():
Number.isNaN(a)?b=!0:null==a?b=!0:(b=0===a.length,a="object"===typeof a&&0===Object.keys(a).length,b=b||a);return b}function ia(a,b){let c;1===a.length?[c]=a:c=a[b];return c}function F(a){let b;null===a||void 0===a||"undefined"===typeof a.length||"string"===typeof a?b=a:1===a.length?[b]=a:b=[...a];return b}function va(a){function b(){return`${L} : ${N}`}function c(h){const l=[];h.forEach(n=>{const m=pa(n);m?l.push(`'${m}'`):(n=E(n),l.push(n))});return l}function d(h,l,n,m,t){var w=n.split("() ")[0];
L+=1;y[w].CHECKS+=1;ja&&R([L],"background: #ee0; color: #00F");if(h){N+=1;y[w].FAILURES+=1;Ka(b());l=` ${l}() ${n} `;if("string"===typeof h)l=h;else{n=l;const [r,A,G]=h;h=c(m);1<h.length?(h=`[${h}]`,m=x(m)):(m=x(m),m=m.substring(1,m.length-1));l=E(G);n=n+A+("\n\t\t"+r);w="    ACTUAL TYPES";let La="    ACTUAL VALUE",Ma=" EMPTY ASSERTION";if("valid(arguments, expected_types)"===r||"validExtras(arguments, expected_types)"===r||"validUnion(arguments, expected_types)"===r||"validUnionExtras(arguments, expected_types)"===
r)w="    ACTUAL TYPES",La="    ACTUAL VALUE",Ma="   EXPECTED TYPE";n+=`${"\n\t\t"}${w} ${h}`;n+=`${"\n\t\t"}${La} ${m}`;n+=`${"\n\t\t"}${Ma} ${l}`;n+=`${"\n\t\t"}${"CALLING FUNCTION"} ${t}`;l=n+="\n\t\t"}if(Z)throw l;aa&&console.log(l)}}function e(h){h=h.toString().match(gb);const l=`${h[0]})`.replace(/^function /,"");h[2].split(", ").includes("arguments")&&R(`Parameter 'arguments' shadows arguments object : ${h[0]})`,"background: #ee0; color: #00F");return l}function g(h,l,n){const m=e(n),t=n.apply(null,
l);d(t,n.name,h,l,m)}function f(h,l,n,m){const t=e(m);l=m.apply(l,n);d(l,m.name,h,n,t)}function k(h){return"object"===typeof h?`{ ${Object.keys(h).map(l=>`${l}()`).reduce((l,n)=>`${l}, ${n}`)} }`:`${h.name}()`}function p(h,l,n){if("function"!==typeof h&&"object"!==typeof h)throw h=x(h),l=`${l}, is a not a function nor an object that has a value of '${h}'`,l=q(l,`TC@${n}`),l;}function u(h,l){const n=k(l);if(void 0===h)throw q(`The function to be checked by ${n} is 'undefined', maybe namespace issue.`,
"TC@05");if(h===l)throw h=`_ParametersCheck you cannot use ${h.name}() to test`+`${l.name}(), they must be different functions`,h=q(h,"TC@28"),h;}function B(h){y[h]?y[h].PRE+=1:y[h]={PRE:1,POST:0,["CHECKS"]:0,["FAILURES"]:0}}function H(h){y[h]?y[h].POST+=1:y[h]={PRE:0,POST:1,["CHECKS"]:0,["FAILURES"]:0}}function I(h,l,n){const m=h.name;return new Proxy(h,{apply(t,w,r){ba(b());z&&l&&(B(m),"undefined"===typeof w?g(`${m}${"() "}${"PRE-FUNC:"}`,r,l):f(`${m}${"() "}${"PRE-FUNC:"}`,w,r,l));t=t.apply(w,
r);z&&n&&(H(m),"undefined"===typeof w?g(`${m}${"() "}${"POST-FUNC:"}`,[t],n):f(`${m}${"() "}${"POST-FUNC:"}`,w,[t],n));return t}})}function S(h,l,n,m){const t=new Set;n&&Object.keys(n).forEach(r=>t.add(r));m&&Object.keys(m).forEach(r=>t.add(r));let w=!1;Object.isFrozen(l)&&(w=!0,l=Object.assign({},l));t.forEach(r=>{if(r!==h){let A=!1;n&&(A=n[r]||!1);let G=!1;m&&(G=m[r]||!1);l[r]&&(l[r]=I(l[r],A,G))}});w&&Object.freeze(l);return l}function ka(h,l){return"function"===typeof h?h:"undefined"===typeof h?
!1:h[l]}function hb(h,l,n){const m=h.name,t=ka(l,m),w=ka(n,m);return new Proxy(h,{apply(){},construct(r,A,G){ba(b());z&&t&&(B(m),g(`${m}${"() "}${"PRE-CLASS:"}`,A,t));r=Reflect.construct(r,A,G);r=S(m,r,l,n);z&&w&&(H(m),f(`${m}${"() "}${"POST-CLASS:"}`,r,[r],w));return r}})}function ib(h,l,n){const m=h.name,t=ka(l,m),w=ka(n,m);return new Proxy(h,{apply(r,A,G){ba(b());z&&t&&(B(m),g(`${m}${"() "}${"PRE-OBJ:"}`,G,t));r=r.apply(A,G);r=S(m,r,l,n);z&&w&&(H(m),g(`${m}${"() "}${"PRE-OBJ:"}`,[r],n[m]));return r},
construct(r,A){ba(b());z&&t&&(B(m),g(`${m}${"() "}${"POST-OBJ:"}`,A,t));r=new r(...A);r=S(m,r,l,n);z&&w&&(H(m),f(`${m}${"() "}${"POST-OBJ:"}`,r,[r],w));return r}})}function jb(h,l,n){var m=arguments.length;if(2!==m&&3!==m)throw q(`TypeCzech.confirmParameters() needs 2 or 3 parameters, not ${m}`,"TC@52");if(Na.has(h)){var t=`${h.name}() is already proxied with ${h.name}`;t=q(t,"TC@04");throw t;}if("function"!==typeof h)throw t=`The first parameter to TypeCzech.check(), target_proxy is not a function, but is instead ${x(h)}`,
t=q(t,"TC@06"),t;if(l)for(var w in l)m=l[w],u(h,m),p(m,"TypeCzech.check() 2nd parameter, PRE-CHECK()",31);if(n)for(t in n)w=n[t],u(h,w),p(w,"TypeCzech.check() 3rd parameter, POST-CHECK()",31);Ha(h)?t=hb(h,l,n):(t=v(l),w=v(n),t="Object"===t||"Object"===w?ib(h,l,n):I(h,l,n));Na.add(t);return t}var T=arguments.length;if(1<T)throw q(`TypeCzech.confirmParameters() needs 0 or 1 parameters, not ${T}`,"TC@53");let ba=()=>"",Ka=()=>"",y=[],L=0,N=0,z=!1;T=(h,l,n)=>h;T=wa?jb:T;if(wa){a&&"Object"!==v(a)&&R(["_ParametersCheck - arg_check_events is not an Object with onStart(), onCheck(), onError() ",
a],"background: #ee0; color: #F00");R(["TypeCzech-init","ver 4.0",Z?"THROW-EXCEPTIONS":"",aa?"LOG-ERRORS":"",J?"UNDEF-OK":"",ja?"CONSOLE-COUNT":"",a],"background: #cc0; color: #080");if(void 0!==a.onStart)a.onStart("Start");void 0!==a.onCheck&&(ba=a.onCheck);void 0!==a.onError&&(Ka=a.onError);z=!0}return{confirmParameters:T,checkBegin_:function(){z=!0;N=L=0},checkTally_:function(){return L},checkEnd_:function(){z=!1},failureTally_:function(){return N},failureRatio_:function(){return`${N}/${L}`},stats_:function(h){"undefined"===
typeof h?(h=y,h[0]=`Total Checks : ${L}`,h[1]=`Failure Count: ${N}`):h={possible_type:y[h]};return h},statsReset_:function(){y=[];N=L=0;z=z=!1}}}function ca(a,b){b||(b={});"function"===typeof b&&(b={cmp:b});var c="boolean"===typeof b.cycles?b.cycles:!1,d=b.cmp&&function(g){return function(f){return function(k,p){return g({key:k,value:f[k]},{key:p,value:f[p]})}}}(b.cmp),e=[];return function k(f){f&&f.toJSON&&"function"===typeof f.toJSON&&(f=f.toJSON());if(void 0!==f){if("number"==typeof f)return isFinite(f)?
""+f:"null";if("object"!==typeof f)return JSON.stringify(f);var p;if(Array.isArray(f)){var u="[";for(p=0;p<f.length;p++)p&&(u+=","),u+=k(f[p])||"null";return u+"]"}if(null===f)return"null";if(-1!==e.indexOf(f)){if(c)return JSON.stringify("__cycle__");throw new TypeError("Converting circular structure to JSON");}var B=e.push(f)-1,H=Object.keys(f).sort(d&&d(f));u="";for(p=0;p<H.length;p++){var I=H[p],S=k(f[I]);S&&(u&&(u+=","),u+=JSON.stringify(I)+":"+S)}e.splice(B,1);return"{"+u+"}"}}(a)}function Oa(a,
b){a=Object.entries(a);const [c,d]=a[0];b=x(b);return q(`Index '${c}' is supposed to be a '${d}', but is missing : ${b}`,"TC@03")}function O(a,b,c){let d="";const e=v(a),g=v(b);void 0===b?d="":e!==g?(a=E(a),d=q(`Parameter is meant to be '${g}' but is`+` of the wrong type of '${e}':${a}`,"TC@36")):"Array"===g?("Array"===v(b[0])&&(1===b.length?xa(a,b[0],c):xa(a,b,c)),d=Pa(a,b,c)):"Object"===g&&(d=Qa(a,b,c));return d}function Pa(a,b,c){let d="";if(1===b.length&&1<a.length)d=Ra(a,b[0],c);else{const e=
Array.from(b);b=e.length;a.forEach((g,f)=>{const k=v(g),p=ia(e,f);C(p)?d+=O(g,p,c):(g=K(ia(e,f)),g===k||"TYPE-EXTRAS"===c&&void 0===g||J&&"null"===k||J&&"undefined"===k||(d=Sa(g,f,k)));delete e[f]});1!==b&&a.length<b&&(d=Oa(e,a))}return d}function Qa(a,b,c){const d=[],e={...b};Object.entries(a).forEach(f=>{let k="";const [p,u]=f;C(u)?(k+=O(a[p],b[p],c),delete e[p]):Object.prototype.hasOwnProperty.call(e,p)?(k+=Ta(e,p,u),delete e[p]):"TYPE-VERIFY"===c&&(k=q(`Extra key in checked object - (${p}:'${u}')`,
"TC@39"));k&&d.push(k)});let g="";0<d.length&&d.forEach(f=>{g+=f});return g+=ua(e)}function Ua(a,b){b=K(b);var c="";if("null"===b||"undefined"===b)c=q(`The type '${b}' is not a valid type`,"TC@17");else if(qa(b))c=v(a),c=c===b?"":"Array"===c?`The variable '[]', which is a 'Array', is not a '${b}'`:"Object"===c?`The variable '{}', which is a 'Object', is not a '${b}'`:"undefined"===c?q(`The variable '${void 0}', is not a '${b}'`,"TC@34"):`The variable '${a}', which is a '${c}', is not a '${b}'`;else{var d=
!1;null!==a&&"undefined"!==typeof a&&"object"===typeof Object.getPrototypeOf(a)&&(a=a.constructor,(d=Ga(a))?a=d:(d="",a.toString().startsWith("function ")&&(d=a.name),a=d),d=a);d!==b&&(c="",Ia(b)||(c=Va[b]?q(`The type '${b}' is not a valid type, but it looks just like '${Va[b]}'`,"TC@33"):q(`The type '${b}' is not the correct class`,"TC@16")))}return c}function U(a,b,c){return C(b)?O(a,b,c):Ua(a,b)}function Wa(a,b){a=Object.entries(a);const [c,d]=a[0];b=E(b);return q(`INDEX '${c}' is promised to be a '${d}', but is missing : ${b}`,
"TC@29")}function Xa(a,b,c,d,e,g){e=E(d);return"EMPTY-ERROR"===a||"EM-ER"===a?Y(b)?q(`INDEX '${c}' is erroneously empty :`,"TC@30"):"":"EMPTY-OK"===a||"EM-OK"===a||"EMPTY-IGNORE"===a||"EM-IG"===a?M(d[c],a,g):"String"===v(a)?q(`INDEX '${c}' is incorrect  type, '${a}', only`+` [EM-ER, EMPTY-ERROR, EMPTY-OK, EM-OK, EMPTY-IGNORE, EM-IG] allowed  : ${e}`,"TC@32"):M(d[c],a,g)}function kb(a,b,c,d){b=x(JSON.stringify(b));return q(`The parameter array ${a} does not have the same number of elements as ${b}. `+
` Lengths are different ${c} !== ${d}.`,"TC@20")}function M(a,b,c){const d=v(b);void 0===b?a="":"Array"===d?("Array"===v(b[0])&&(1===b.length&&ya(a,b[0],c),ya(a,b,c)),a=Ya(a,b,c)):a="Object"===d?Za(a,b,c):za(a,b);return a}function za(a,b){let c="";b=X(b);const d=v(a);if("EMPTY-ERROR"===b){const e=v(a);Aa(e)?Y(a)&&("Object"===d&&(a=" { } "),c=q(`${b} states '${d}' must not `+`be empty for the value '${a}'`,"TC@24")):c=q(`A '${d}' cannot be empty, so the state`+` of '${b}' is illegal for the value '${a}'`,
"TC@25")}else"EMPTY-OK"!==b&&"EMPTY-IGNORE"!==b&&(c=q(`Must 'EMPTY-OK' or 'EMPTY-ERROR' not '${b}'`,"TC@11"));return c}function $a(a,b,c){return C(b)?M(a,b,c):za(a,b)}function la(a,b,c){return 1!==b.length||"EMPTY-OK"!==b[0]&&"EM-OK"!==b[0]?$a(a,b,c):q("Completely pointless as checking with ['EM-OK'] or ['EMPTY-OK'] matches everything","TC@12")}function Ba(a,b){const [c,d]=b;let e=b="",g=!1;d.forEach(f=>{let k=f;"String"===f&&1===c.length&&(k=[f]);f=la(c,k,a);""===f?g=!0:e=f});g||(b=e);return b}function Ca(a,
b){const [c,d]=b;let e=b="",g=!1;d.forEach(f=>{let k=f;"String"===f&&1===c.length&&(k=[f]);f=U(c,k,a);""===f?g=!0:e=f});g||(b=e);return b}function ab(a){let b=a;a=a[0];Array.isArray(a)&&(b=a);b.forEach(c=>{if("object"===typeof c)Da=c;else if("UNDEF-OK"===c)J="UNDEF-OK";else if("DEBUG-CONSOLE-TRACE"===c)ta="DEBUG-CONSOLE-TRACE";else if("THROW-EXCEPTIONS"===c)Z="THROW-EXCEPTIONS";else if("LOG-ERRORS"===c)aa="LOG-ERRORS";else if("CONSOLE-COUNT"===c)ja="CONSOLE-COUNT";else if("NO-CHECKING"!==c)if("DEBUG-ERROR-TAGS"===
c)sa="DEBUG-ERROR-TAGS";else if(""!==c)throw c=`Not THROW-EXCEPTIONS/LOG-ERRORS/UNDEF-OK/DEBUG-CONSOLE-TRACE/NO-CHECKING, unknown : ${E(c)}`,c=q(c,"TC@21"),c;});bb=wa=!(!Z&&!aa);return[Z,aa,J,ta,ja,sa]}function da(a,b,c){var d="";if(2!==a.length)d=q(`TypeCzech.${b}() has 2 ${"arguments"} not ${a.length}`,"TC@14");else{const [g,f]=a;var e=v(g);const k=v(f),p=JSON.stringify(e);a=f;"string"!==typeof f&&(a=JSON.stringify(f));"Array"===e&&"Array"!==k?(b=1<g.length,"Array"!==f&&"A"!==f&&b&&(d=g,b=K(a),
d=q("Comparing actual [] parameter, with a"+` value of ['${d}'], against the expected shape of ${b}. They should be the same type.`+` You cannot compare an array with a non-array; both []s, or both ${b}s.`,"TC@58"),a=ha(a),d=[c,d,a])):"Array"===k&&"Array"!==e?(d=g,b=e,e=K(a),d=q(`Comparing actual '${b}' parameter,`+` with a value of '${d}', in relation to the expected shape of ${e}. They should be the`+` same type. You cannot compare an array with a non-array; both []s, or both '${b}'s.`,"TC@49"),
a=ha(a),d=[c,d,a]):"Array"!==k&&("Object"===k?"Object"!==e&&(d=q(`TypeCzech.${b}() called with '{}' against '!{}'.`+` Contrasting '${p}' with '${a}'.`,"TC@07")):"String"!==k&&(d=q(`TypeCzech.${b}() called with 'a-variable' and 'not-a-variable type'.`+` Matching '${p}' with '${a}'.`+` Preferably try TypeCzech.${b}(12, 'Number')`,"TC@50")))}return d}function ea(a,b){let c="";if(2!==a.length)c=q(`TypeCzech.${b}() needs 2 parameters, not ${a.length}`,"TC@51");else{a=a[1];const d=JSON.stringify(a);"Array"!==
v(a)&&(c=q(`TypeCzech.${b}() called with a second parameter`+` as a non-array shape of ${d}`,"TC@15"))}return c}function V(a){if(160>a.length)var b=a;else b=a.substring(0,100),a=a.substring(a.length-50),b=`${b} ${"<<<<<<...>>>>>>"} ${a}`;return b}function cb(a,b){var c="";if(a!==b){c=0;for(var d=!1;a[c]===b[c];){if(c===a.length||c===b.length){d=!0;break}c+=1}const [g,f]=[c,d];var e=a.length;d=b.length;f?e>d?(c=0===d?"``":b,e=a.substring(g),b="``"):(c=0===e?"``":a,e="``",b=a.substring(g)):(c=0===g?
"``":a.substring(0,g),e=0===e?"``":a.substring(g),b=0===d?"``":b.substring(g));a=e;c=V(c);a=V(a);b=V(b);c=x(`${"\n\t\t"}START-SAME ~ ${c}`);a=x(`${"\n\t\t"}  PRE-DIFF ~ ${a}`);b=x(`${"\n\t\t"} POST-DIFF ~ ${b}`);c=`${c}${a}${b}`}return c}function Ea(a){let b=!1;a&&1===a.length&&(a=a[0],b="Array"===v(a)?Ea(a):!0);return b}let bb=!0,D,Da=!1,wa=!1;const P={},Na=new WeakSet;let Z=!1,aa=!1,J=!1,ja=!1,sa=!1,ta=!1;const gb=/([^(]*\()([^)]*)/,Ja={"EM-OK":"EMPTY-OK","EM-ER":"EMPTY-ERROR","EM-IG":"EMPTY-IGNORE"},
na="Array BigInt Boolean Date Function Number Object RegExp String Symbol".split(" "),Va={array:"Array",bigint:"BigInt",boolean:"Boolean",date:"Date",function:"Function",number:"Number",object:"Object",regexp:"RegExp",string:"String",symbol:"Symbol"},eb=new Set(na),ra={A:"Array",I:"BigInt",B:"Boolean",D:"Date",F:"Function",N:"Number",O:"Object",R:"RegExp",S:"String",Y:"Symbol"},ma={backBlink:a=>{document.body.style.background=a;setTimeout(()=>{document.body.style.background="white"},100)},onStart:()=>
ma.backBlink("green"),onCheck:()=>ma.backBlink("blue"),onError:()=>ma.backBlink("red")},Aa=a=>"Array"===a?!0:"Object"===a?!0:"String"===a?!0:"RegExp"===a?!0:"Date"===a?!0:"Number"===a,fa={decycle:function(a){var b=[],c=[];return function f(e,g){var k,p;if(!("object"!==typeof e||null===e||e instanceof Boolean||e instanceof Date||e instanceof Number||e instanceof RegExp||e instanceof String)){for(k=0;k<b.length;k+=1)if(b[k]===e)return{$ref:c[k]};b.push(e);c.push(g);if("[object Array]"===Object.prototype.toString.apply(e)){var u=
[];for(k=0;k<e.length;k+=1)u[k]=f(e[k],g+"["+k+"]")}else for(p in u={},e)Object.prototype.hasOwnProperty.call(e,p)&&(u[p]=f(e[p],g+"["+JSON.stringify(p)+"]"));return u}return e}(a,"$")},retrocycle:function(a){var b=/^\$(?:\[(?:\d+|"(?:[^\\"\u0000-\u001f]|\\([\\"\/bfnrt]|u[0-9a-zA-Z]{4}))*")\])*$/;(function e(d){var g,f;if(d&&"object"===typeof d)if("[object Array]"===Object.prototype.toString.apply(d))for(g=0;g<d.length;g+=1){if((f=d[g])&&"object"===typeof f){var k=f.$ref;"string"===typeof k&&b.test(k)?
d[g]=eval(k):e(f)}}else for(g in d)"object"===typeof d[g]&&(f=d[g])&&(k=f.$ref,"string"===typeof k&&b.test(k)?d[g]=eval(k):e(f))})(a);return a}},xa=(a,b,c)=>{let d;a.forEach((e,g)=>{d="";d=1===b.length?d+O(e,b,c):d+O(e,b[g],c)});return d},Ra=(a,b,c)=>{let d="";const e=K(b);a.forEach((g,f)=>{const k=v(g);C(e)?d=U(g,e,c):e===k||J&&"null"===k||J&&"undefined"===k||(g=x(g),d=q(`INDEX '${f}' is asserted to be a '${e}',`+` but is fallaciously a '${k}' : ${g}`,"TC@45"))});return d},Sa=(a,b,c)=>q(` INDEX '${b}' is assumed to be a '${a}',`+
` but is mistakenly a '${c}'`,"TC@44"),Ta=(a,b,c)=>{let d="";a=K(a[b]);if(qa(a)){const e=v(c);a===e||J&&"null"===e||J&&"undefined"===e||("undefined"===typeof c?d=q(`Key '${b}' was given to be a '${a}' but was instead 'undefined'`,"TC@41"):"null"===e?d=q(`Key '${b}' was determined to be a '${a}' but was instead 'null'`,"TC@42"):(c=x(c),d=q(`Property '${b}' is indicated to be a '${a}',`+` but is inaccurately a '${e}' : ${c}`,"TC@43")))}else d=q(`The type '${a}' is not valid`,"TC@40");return d},ya=(a,
b,c)=>{let d="";const e=v(a);"Array"!==e?(a=x(a),d=q(`Variable 'check_array' must be an array but is instead a '${e}', : ${a}`,"TC@97")):a.forEach((g,f)=>{1===b.length?((g=M(g,b,c))&&(g+=` inside [${f}]`),d+=g):d+=M(g,b[f],c)});return d},Ya=(a,b,c)=>{let d="";var e=a.length;const g=b.length,f=x(JSON.stringify(a));if(0===e)d=q(`The parameter array ${f} is empty.`,"TC@19");else if("EMPTY-EXTRAS"!==c&&1<g&&g!==e)d=kb(f,b,e,g);else{const k=Array.from(b),p=k.length;e=v(a);"Array"!==e?d=q(`Variable 'check_array' must be an array but is a '${e}', : ${f}`,
"TC@96"):a.forEach((u,B)=>{const H=v(u),I=ia(k,B);C(I)?d+=M(a[B],I,c):1!==p&&delete k[B];(u=Xa(I,u,B,a,H,c))&&(d=u)});1!==p&&"EMPTY-EXTRAS"!==c&&a.length!==p&&(d=Wa(b,a))}return d},db=(a,b,c)=>{let d="";a=X(a);if("EMPTY-ERROR"===a){const e=v(b);Aa(e)?Y(b)&&(b=E(b),d=q(`'${c}' is a '${e}' which is reputed `+`to be '${a}' but has a value of ${b}.`,"TC@08")):d=q(`Cannot be invalid '${c}' ${a}' is a ${b} :: ${e}`,"TC@09")}else"EMPTY-OK"!==a&&"EMPTY-IGNORE"!==a&&(c=`bad invalid key '${x(a)}', must be either EMPTY-OK -ER -IG`,
d=q(c,"TC@10"));return d},Za=(a,b,c)=>{const d=[],e={...b};Object.entries(a).forEach(f=>{var k="";const [p,u]=f;f=X(e[p]);C(u)?(f=X(b[p]),Y(u)&&"EMPTY-ERROR"===f?(k=E(u),k=q(`Key '${p}' was understood to be '${f}' but was rather '${k}'`,"TC@26")):k+=M(a[p],f,c),delete e[p]):Object.prototype.hasOwnProperty.call(e,p)?(k=db(f,u,p),delete e[p]):"EMPTY-VERIFY"===c&&(k=q(`Extra key in checked object - (${p}:'${u}')`,"TC@27"));k&&d.push(k)});let g="";0<d.length&&d.forEach(f=>{g+=f});return g+=ua(e)};ab(W);
D=Da?va(Da):va(!1);return{_ParametersCheck:va,_arrayOfOneType:Ra,_arrayof1:Ea,_aTypeOf:v,_canBeEmpty:Aa,_coloredConsole:R,_consoleError:q,_cycle:fa,_doUnionEmpty:Ba,_doUnionShape:Ca,_doubleToSingleQuotes:ha,_emptyArrayInArray:ya,_emptyArrayTypes:Ya,_emptyCheck:la,_emptyCollectionTypes:Za,_emptyContainer:M,_emptyError:Xa,_emptyErrorMess:Wa,_emptyKeysChecked:db,_emptyScalar:za,_emptyVariable:$a,_fast_json_stable_stringify:ca,_isAClass:Ha,_isBuiltInType:Ia,_isCollection:C,_isEmpty:Y,_isScalar:function(a){return!C(a)},
_isPlainJsType:qa,_jsonStr:E,_missingKey:ua,_unionChecks:ea,_refDiff:cb,_shapeArrayInArray:xa,_shapeArrayTypes:Pa,_shapeCheck:function(a,b,c){return U(a,b,c)},_shapeCollectionTypes:Qa,_shapeContainer:O,_shapeErrorMess:Oa,_shapeObjectInArray:(a,b,c)=>{let d="";const e=v(b),g=v(a);if("Array"!==g){const f=x(a);d=q(`Variable 'check_array' must be an array but is instead a '${g}', : ${f}`,"TC@98")}else a.forEach((f,k)=>{var p=v(f);"Object"===e?(p=O(f,b,c))&&(d=q(`Index '${k}' - ${p}`,"TC@01")):b!==p&&
(f=x(a),d=q(`Index '${k}' is presumed to be a '${b}',`+` but is incorrectly a '${p}' : ${f}`,"TC@02"))});return d},_shapePropertyType:Ta,_shapeScalar:Ua,_shapeVariable:U,_shortToLongEmpty:X,_shortToLongType:K,_shrinkDiffs:V,_specParameters:ab,_toStr:x,_twoArrays:da,_typeFromArray:ia,_wrongType:Sa,TYPE_CZECH_EVENTS:ma,CZECH_ERROR_INDENT:"\n\t\t",is_active:bb,arrayOfOneParameter:function(a){let b=!1;1===a.length&&1===a[0].length&&(b=Ea(a[0]));return b},check:function(a,b,c){return"undefined"===typeof c?
D.confirmParameters(a,b,!1):D.confirmParameters(a,b,c)},checkBegin:function(){return D.checkBegin_()},checkEnd:function(){return D.checkEnd_()},checkTally:function(){return D.checkTally_()},failureRatio:function(){return D.failureRatio_()},failureTally:function(){return D.failureTally_()},mutateSnapshot:function(a,b,c){var d=arguments.length;if(3!==d)throw q(`TypeCzech.mutateSnapshot() needs 3 parameters, not ${d}`,"TC@55");if(!C(c))throw d=`TypeCzech.mutateSnapshot()'s 3rd parameter is not an array/object but instead a '${v(c)}'`,
d=q(d,"TC@56"),d;d=`${a}-${b}`;var e=fa.decycle(c);e=ca(e);e={func_name:a,var_name:b,collection_ref:c,pre_collect_str:e};P[d]?P[d].push(e):P[d]=[e];d=fa.decycle(P);ca(d)},mutated:function(a,b){var c=`${a}-${b}`,d="";if(P[c]){c=P[c].pop();const {collection_ref:e,pre_collect_str:g}=c;c=fa.decycle(e);c=ca(c);if(g!==c){const f=x(g);d=x(c);a=`The reference variable '${b}' in function '${a}()' changed values`;b=V(f);d=V(d);b=`${"\n\t\t"}from ${b}`;d=`${"\n\t\t"}  to ${d} ${"\n\t\t"}`;c=cb(g,c);d=q(`${a}${b}${d}${c}`,
"TC@48")}}else d=q(`No record of a mutateSnapshot('${c}', a_var)`,"TC@47");c=fa.decycle(P);ca(c);return d},objectIsA:function(a,b){a=oa(a);let c=!1;a&&(c=a.includes(b));return c},objectInterface:function(a,b){a=F(a);let c="";for(const d in b){let e="";const g=K(b[d]);if("string"!==typeof g)e=`objectInterface() {${d}:'${g}'} has a bad type - not string`;else if("Function"!==g&&"Object"!==g)e=`objectInterface() only allows functions and objects, not {${d}:'${g}'}`;else{const f=a[d];f||(e="missing key");
const k=v(f);g!==k&&(e=`actual type of '${d}' is '${k}', with a value `+`of '${f}', not the expected '${g}' type`)}e&&!c&&(c=e)}c&&(c=`Interface mismatches : ${c}`);return c},objectPrototypes:oa,objectType:pa,stats:function(a){return D.stats_(a)},statsReset:function(){return D.statsReset_()},valid:function(a,b){a=F(a);let c=da([a,b],"valid","valid(arguments, expected_types)");""===c&&(c=(a=U(a,b,"TYPE-VERIFY"))?["valid(arguments, expected_types)",a,b]:"");return c},validExtras:function(a,b){a=F(a);
let c=da([a,b],"validExtras","validExtras(arguments, expected_types)");""===c&&(c=(a=U(a,b,"TYPE-EXTRAS"))?["validExtras(arguments, expected_types)",a,b]:"");return c},validUnion:function(a,b){a=F(a);let c=ea([a,b],"validUnion");""===c&&(c=(a=Ca("TYPE-VERIFY",[a,b]))?["validUnion(arguments, expected_types)",a,b]:"");return c},validUnionExtras:function(a,b){a=F(a);let c=ea([a,b],"validUnionExtras");""===c&&(c=(a=Ca("TYPE-EXTRAS",[a,b]))?["validUnionExtras(arguments, expected_types)",a,b]:"");return c},
valueless:function(a,b){a=F(a);let c=da([a,b],"valueless","valueless(arguments, expected_emptys)");""===c&&(c=(a=la(a,b,"EMPTY-VERIFY"))?["valueless(arguments, expected_emptys)",a,b]:"");return c},valuelessExtras:function(a,b){a=F(a);let c=da([a,b],"valuelessExtras","valuelessExtras(arguments, expected_emptys)");""===c&&(c=(a=la(a,b,"EMPTY-EXTRAS"))?["valuelessExtras(arguments, expected_emptys)",a,b]:"");return c},valuelessUnion:function(a,b){a=F(a);let c=ea([a,b],"valuelessUnion");""===c&&(c=(a=
Ba("EMPTY-VERIFY",[a,b]))?["valuelessUnion(arguments, expected_emptys)",a,b]:"");return c},valuelessUnionExtras:function(a,b){a=F(a);let c=ea([a,b],"valuelessUnionExtras");""===c&&(c=(a=Ba("EMPTY-EXTRAS",[a,b]))?["valuelessUnionExtras(arguments, expected_emptys)",a,b]:"");return c}}}Q.type_czech=0<arguments.length?Fa(...arguments):"undefined"!==typeof Q.TYPE_CZECH_COMMANDS&&0<Q.TYPE_CZECH_COMMANDS.length?Fa(Q.TYPE_CZECH_COMMANDS):{check:W=>W,stats:W=>W,is_active:!1};return Q.type_czech}})(the_exports);
